cv:
  resource:
    url: http://localhost:8082/cvdetails
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_ON_EXIT=FALSE
    username: postgres
  jpa:
    properties:
      hibernate:
        ddl-auto: create
        show_sql: true